"""Render deals as HTML (email) and Markdown (committed report artifact)."""

from __future__ import annotations

from .models import Deal, Listing


def _price(v) -> str:
    return f"${v:,.0f}" if isinstance(v, (int, float)) else "—"


def cheapest(listings: list[Listing]) -> list[Listing]:
    priced = [l for l in listings if l.price is not None]
    return sorted(priced, key=lambda l: l.price)[:10]


def markdown_report(deals: list[Deal], listings: list[Listing],
                    today: str, query: str) -> str:
    lines = [
        f"# Audi deal report — {today}",
        "",
        f"**Search:** {query}",
        f"**Listings scanned:** {len(listings)}  ·  **Deals flagged:** {len(deals)}",
        "",
    ]

    if deals:
        lines += ["## 🔥 Flagged deals", ""]
        for d in deals:
            l = d.listing
            lines.append(f"### {l.label} — {_price(l.price)}")
            lines.append("")
            lines.append(f"- **Why:** {'; '.join(d.reasons)}")
            lines.append(f"- MSRP: {_price(l.msrp)}  ·  Asking: {_price(l.price)}"
                         + (f"  ·  was {_price(d.previous_price)}" if d.previous_price else ""))
            lines.append(f"- Dealer: {l.location()}")
            if l.miles is not None:
                lines.append(f"- Miles: {l.miles:,.0f}")
            if l.url:
                lines.append(f"- [View listing]({l.url})")
            lines.append(f"- VIN: `{l.vin}`")
            lines.append("")
    else:
        lines += ["_No listings crossed the alert thresholds today._", ""]

    cheap = cheapest(listings)
    if cheap:
        lines += ["## 💸 Cheapest in inventory right now", "",
                  "| Price | MSRP | Vehicle | Dealer | VIN |",
                  "|------:|-----:|---------|--------|-----|"]
        for l in cheap:
            lines.append(
                f"| {_price(l.price)} | {_price(l.msrp)} | {l.label} "
                f"| {l.location()} | `{l.vin}` |"
            )
        lines.append("")

    return "\n".join(lines)


def html_email(deals: list[Deal], listings: list[Listing],
               today: str, query: str) -> str:
    def card(d: Deal) -> str:
        l = d.listing
        link = (f'<a href="{l.url}">View listing →</a>' if l.url else "")
        prev = (f' · was {_price(d.previous_price)}' if d.previous_price else "")
        return f"""
        <div style="border:1px solid #e2e2e2;border-radius:10px;padding:14px;margin:10px 0;">
          <div style="font-size:16px;font-weight:600;">{l.label} — {_price(l.price)}</div>
          <div style="color:#c0392b;font-weight:600;margin:4px 0;">{'; '.join(d.reasons)}</div>
          <div style="color:#555;font-size:13px;">
            MSRP {_price(l.msrp)} · Asking {_price(l.price)}{prev}<br/>
            {l.location()}{(' · ' + f'{l.miles:,.0f} mi') if l.miles is not None else ''}<br/>
            <span style="color:#888;">VIN {l.vin}</span>
          </div>
          <div style="margin-top:6px;">{link}</div>
        </div>"""

    deals_html = "".join(card(d) for d in deals) or \
        "<p>No listings crossed the alert thresholds today.</p>"

    cheap_rows = "".join(
        f"<tr><td style='text-align:right;padding:4px 10px;'>{_price(l.price)}</td>"
        f"<td style='text-align:right;padding:4px 10px;'>{_price(l.msrp)}</td>"
        f"<td style='padding:4px 10px;'>{l.label}</td>"
        f"<td style='padding:4px 10px;'>{l.location()}</td></tr>"
        for l in cheapest(listings)
    )

    return f"""<!doctype html><html><body style="font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#222;max-width:680px;margin:0 auto;">
      <h2>Audi deal report — {today}</h2>
      <p style="color:#666;">{query}<br/>
      Scanned {len(listings)} listings · {len(deals)} flagged.</p>
      <h3>🔥 Flagged deals</h3>
      {deals_html}
      <h3>💸 Cheapest in inventory</h3>
      <table style="border-collapse:collapse;font-size:13px;">
        <tr style="background:#f5f5f5;"><th style="padding:4px 10px;">Price</th><th style="padding:4px 10px;">MSRP</th><th style="padding:4px 10px;">Vehicle</th><th style="padding:4px 10px;">Dealer</th></tr>
        {cheap_rows}
      </table>
      <p style="color:#aaa;font-size:11px;margin-top:24px;">Generated by audi-deal-scraper.</p>
    </body></html>"""
